version: "3.9"
services:

  backend:
    container_name: backend
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually
    depends_on:
      - frontend


  database:
    container_name: database
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually
    depends_on:
      - backend


  frontend:
    container_name: frontend
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually

  worker:
    container_name: worker
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually
    depends_on:
      - backend


  redis:
    container_name: redis
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually
    depends_on:
      - backend


  nginx:
    container_name: nginx
    image: image_registry_url                # Manually(Optional if build)
    build:
      context: ./path                        # Manually
      dockerfile: ./path/.../Dockerfile      # Manually
    environment:
      - ENV_NAME:ENV_VALUE                   # Manually
    ports:
      - "1111:1111"                          # Manually
    volumes:
      - ./path:/app                          # Manually
    depends_on:
      - backend

      - frontend

